### ISSUE TITLE
"arrays used as indices must be of integer (or boolean) type"

### ISSUE THREAD

**Issue by sjyzhu** [mne-tools/mne-icalabel#126] opened 2023-03-16 14:30 UTC
#### Describe the bug

When I was running "label_components", an error occurred: 
  "arrays used as indices must be of integer (or boolean) type"

#### Steps to reproduce
IDE: jupyter notebook
python 3.9.12
mne 1.3.1
mne-iclabel 0.4

```
raw_filt = raw_filt.filter(l_freq=1, h_freq=None)
ica = mne.preprocessing.ICA(n_components=8, method='picard', max_iter=10000) 
ica.fit(raw_filt)

ic_labels = label_components(raw_filt, ica, method="iclabel")
```

#### Actual results
![Snipaste_2023-03-16_22-22-55](https://user-images.githubusercontent.com/54942196/225649278-c4492ce3-5889-4d3c-bb78-ca9a8ceeb914.png)

**Comment by mscheltienne** [comment] 2023-03-16 15:27
Indeed a couple of missing error message, can you share the full traceback? Found the lines here https://github.com/mne-tools/mne-icalabel/blob/1c0418b5bfc65ec74e26fcf3770a3ee2eb6f184c/mne_icalabel/iclabel/utils.py#L245

Also, could you save the ICA decomposition with `ica.save` and share the ICA decomposition and the Raw file (you can save it with `raw_filt.save`)?

**Comment by mscheltienne** [comment] 2023-03-16 15:29
Arf, the traceback is incomplete because it's a Jupyter notebook, sneaky `...` on the left side..

**Comment by sjyzhu** [comment] 2023-03-16 16:33
> Can you use the version on `main`?
> 


Sorry, I don't know what `main` means... = =

**Comment by sjyzhu** [comment] 2023-03-16 16:48
> Also, could you save the ICA decomposition with `ica.save` and share the ICA decomposition and the Raw file (you can save it with `raw_filt.save`)?

I'm not sure if I can upload raw files, because these are from confidential patient data.

**Comment by mscheltienne** [comment] 2023-03-16 17:06
`main` means the not-yet-released code, i.e. the version available as of today on the GitHub repository. You can install it in an environment by doing `pip install git+https://github.com/mne-tools/mne-icalabel`. This is to eliminate the possibility of a bug that has already been fixed but has not yet been released.

> I'm not sure if I can upload raw files, because these are from confidential patient data.

Unlucky, as it's difficult to debug if we can not reproduce the error. 
Pinging @yjmantilla who authored the `gdatav4` translation, by any chance does this error look familiar to you?

If you don't mind, I would like to give you a couple of short code snippets that I'd like you to run and return the output here to help us debug the issue further without providing us with the RAW/ICA files. 
Do you only use Jupyter or also other IDEs, and especially do you know how to use breakpoints and debug mode?

**Comment by sjyzhu** [comment] 2023-03-17 01:24
> `main` means the not-yet-released code, i.e. the version available as of today on the GitHub repository. You can install it in an environment by doing `pip install git+https://github.com/mne-tools/mne-icalabel`. This is to eliminate the possibility of a bug that has already been fixed but has not yet been released.

The development version has been installed, and the same bug appeared.
 
> If you don't mind, I would like to give you a couple of short code snippets that I'd like you to run and return the output here to help us debug the issue further without providing us with the RAW/ICA files. Would that be OK with you? Do you only use Jupyter or also other IDEs, and especially do you know how to use breakpoints and debug mode?

OK, I can debug locally through your code.
Is it possible to debug using .py files through vscode?

**Comment by mscheltienne** [comment] 2023-03-17 09:16
Thanks for the help, yes you could debug using VSCode, but if you are not familiar with breakpoints and debug mode, there is no gain compare to Jupyter.

In the following part, `raw` designs the Raw recording used to fit the ICA and `ica` the ICA decomposition. Here are the code snippet:

----------

First let's get some information on your `Raw` recording, especially about the channels:

1. MNE information

Paste in this thread the printed information:

```
from mne import sys_info
print (mne.sys_info())
```

2. `raw.info`

Paste in this thread the printed information:

```
# remove identification information if present
raw.info["description"] = ""
raw.info["device_info"] = dict()
raw.info["experimenter"] = ""
raw.info["subject_info"] = dict()
raw.info["temp"] = None
# display information
print (raw.info)
```

3. Montage

Paste in this thread the figure returned by:

```
raw.get_montage().plot()
```

4. `icawinv`

Return the file `icawinv.npy`:

```
import numpy as np


# Compute icawinv
n_components = ica.n_components_
s = np.sqrt(ica.pca_explained_variance_)[:n_components]
u = ica.unmixing_matrix_ / s
v = ica.pca_components_[:n_components, :]
weights = (u * s) @ v
icawinv = np.linalg.pinv(weights)
del weights
# sanity-check
assert icawinv.shape[-1] == ica.n_components_
assert icawinv.ndim == 2
np.save("icawinv.npy", icawinv, allow_pickle=False)
```

5. `picks` of the topoplot feature

Paste in this thread the printed information:

```
print (ica.ch_names)
```

6. EEG channels coordinates in spherical coordinate system

Return the file `rd.npy` and `th.npy`:

```
import numpy as np

from mne_icalabel.iclabel.utils import _mne_to_eeglab_locs


rd, th = _mne_to_eeglab_locs(raw, ica.ch_names)
np.save("rd.npy", rd, allow_pickle=False)
np.save("th.npy", th, allow_pickle=False)
```

That should be enough for debug and for me to reproduce the error locally.

**Comment by sjyzhu** [comment] 2023-04-07 01:03
> Thanks for the help, yes you could debug using VSCode, but if you are not familiar with breakpoints and debug mode, there is no gain compare to Jupyter.

Sorry for not getting back to you for such a long time. 
After changing a batch of data, the issue did not occur again. Therefore, it should have been a problem with that particular batch of data. 
Thank you very much for your patient guidance !

**Comment by mscheltienne** [comment] 2024-04-27 07:34
Thanks for the reproducible example, it makes debugging way simpler. The error occurs because of a `nan` in the `x` and `y` variables here: https://github.com/mne-tools/mne-icalabel/blob/a7b4c84cd785b77a546f428aa81a5b0c6186d100/mne_icalabel/iclabel/_utils.py#L210-L211

This is due to `raw.set_montage(standard, on_missing='ignore')`, which ignored missing entries. But we actually need a montage with ALL electrodes coordinates to compute the topographic map feature. We could ignore missing channels in the interpolation function, further down the road, but I think we should also issue a warning further up the road. Here is a corrected code snippet for your file:

```
from mne.io import read_raw_fif
from mne.preprocessing import ICA
from mne_icalabel import label_components

fname = r"C:\Users\scheltie\Downloads\test_raw.fif"

raw = read_raw_fif(fname, preload=True)
raw.rename_channels({"Afz": "AFz"})
raw.set_montage("biosemi64")
raw.set_eeg_reference(["LMA", "RMA"])
raw.filter(l_freq=1, h_freq=100, picks=None)
raw.drop_channels(["LMA", "RMA"])
ica = ICA(
    n_components=0.999999,
    method="infomax",
    fit_params=dict(extended=True),
    max_iter="auto",
    random_state=1,
)
ica.fit(raw, picks=["eeg"])
ic_labels = label_components(raw, ica, method="iclabel")
```

I'll think about it and open a PR to close this issue.

**Closed** 2024-04-27 08:56 UTC

**Comment by GABowers** [comment] 2024-04-27 14:15
Okay great, thanks! So in general, I should try to set the montage without ignoring anything?

It looks like you drop the mastoids before ICA. Any particular reason? I tried it with and without that and it works either way.

**Comment by mscheltienne** [comment] 2024-04-27 16:24
Exactly, I this case to do so, one channel had to be renqmed5to match the name in the montage.
